
== archive


....
Keynote Hochschule für Architektur Basel FHNW
Masterstudiengang Architektur

Stimme - Körper- Räume

May 29
....

'''
....
Stefanie Erni, Voice
Marianne Schuppe, Voice

February 14, 20.30
....

https://klangbang.wordpress.com/[Klangbang], Solothurnerstr.4, 4053 Basel

'''
....
Solo Concert
Giacinto Scelsi and a new work by myself

Dezember 6
Rotonde, Große Kunstschau, Worpswede
....

'''

https://www.bettinahelmrich.com/aktuell/[so what? ein Endstück]

Bettina Helmrich, M. Glickson, Tanz
Marianne Schuppe, Sprache
Georg Wolf, Kontrabass
Wolfgang Schliemann, Perkussion

28./29./30.November  19.30 Uhr
Dok 4 Halle, Kassel

'''

Marianne Schuppe - der blumen
weitere Werke von Eva- Maria Houben, Karin Rehnqvist, Kassia, Yoko Ono, Meredith Monk u.a.
Chor Superterz, Ltg. Antoine Beuger

17.{sp} November 19.30
Johanneskirche Köln-Brück

'''

https://www.cabaretvoltaire.ch/de/agenda/hausen.html?day=20191009&times=1570572000,1571608799[Hausen]

Leo Hofmann und Benjamin van Bebber
mit den Gästen Jürg Kienberger, Alla Poppersoni und Marianne Schuppe,

11.{sp} - 20. Oktober 2019
Cabaret Voltaire, Zürich

'''

....
Die Summe (2018/2019) UA
für Chöre und Einzelstimmen
in öffentlichen Räumen

10.-19. September 2019
http://zeitraeumebasel.com/de/2019/spielplan/de-die-summe[Festival ZeitRäume Basel]
....

'''

composers meet composers
mit Antoine Beuger, Jürg Frey, Emmanuelle Waeckerle, Joachim Eckl, Marianne Schuppe

https://www.wandelweiser.de/composers_meet_composers/[heim.art Neufelden,A]

June 23-30

'''


Marianne Schuppe - Salz, Lücke, Zelt (UA) für 8 Stimmen
weitere Werke von Yagüe, Rautavaara, Pärt, Handl, Palestrina u.a.

https://vokalkunst.ch/vokalkunst/konzerte/[Ensemble Voce]

15.Juni 2019 19.30 Uhr La Collégiale St. Ursanne
16.Juni 2019 17 Uhr Kirche Amsoldingen
17.Juni 2019 19.30 Uhr Predigerkirche Basel

'''


Marianne Schuppe - der blumen
weitere Werke von Eva- Maria Houben, Karin Rehnqvist, Kassia, Yoko Ono, Meredith Monk u.a.

Chor Superterz, Ltg. Antoine Beuger
16.{sp} Juni, Epiphaniaskirche Köln-Bickendorf

'''

Marc Kilchenmann - inner core 2/Etüde
Marianne Schuppe - behind 2
Stefan Thut - afore

Marc Kilchenmann, Fagott
Marianne Schuppe, Stimme
Stefan Thut, Violoncello

17.{sp} Mai 2019, 19 Uhr
Münster Bern, Gewölbessal Daniel Heintz

'''

Solo
https://www.dock-basel.ch/[Dock Basel]

25.{sp} Januar, 19.00

'''

notes from the hill and other works
solo and duo with Antoine Beuger
cosy nook, London

January 12

'''

https://www.cafeoto.co.uk/events/marianne-schuppe-slow-songs-nosongs/[slow songs],
https://www.cafeoto.co.uk/events/marianne-schuppe-slow-songs-nosongs/[nosongs]
Cafe Oto, London

January 9, 2019
https://misfitcity.org/category/experimental-music/deep-listening/
scroll down

'''

workshop Stimmimprovisation im Masterstudiengang
Freie Improvisation FHNW Nordwestschweiz
October 26-28th

Werkstattkonzert Sonntag, 28.10. 15 Uhr,
Studio 2, Musikakademie, Leonhardsstr. 6, 4009 Basel

'''

Antoine Beuger: to collect and to recite (2017)

-

Marc Kilchenmann: inner core (2018)
Stefan Thut: afore (2018)
Marianne Schuppe: behind (2018)


for the performance at 18h joined by Antoine Beuger

June 17 th
http://events.solothurnerzeitung.ch/leoonline/portals/azm_soz/veranstaltungen/id/921992/Wort%20und%20Klang%20%E2%80%93%20zwei%20Konzerte%20in%20der%20S%C3%A4ulenhalle/[Solothurn Säulenhalle Landhaus]

'''

der blumen (2017)

Saturday June 9th at 3:30pm,
St. John's Ohio City in Cleveland OH, USA

Friday June 8th at 3pm,
Fairchild Chapel in Oberlin OH , USA

'''

Sotto Voce Vocal Collective, Buffalo NY

premierres my piece der blumen for voices

April 29th 2pm
Unitarian Universalist Church of Buffalo NY

'''


Ungehörte Ordnungen

Marianne Schuppe, Stimme,
Alfred Zimmerlin, Violoncello

23.{sp} April, 19.30
http://www.maison44.ch/content/aktuell_galerie/aktuell.html[Maison 44], Steinenring 44, 4051 Basel


'''

Atelierkonzert

Stefanie Erni, Stimme
Marianne Schuppe, Stimme

Improvisation
Marianne Schuppe - streifen

22.April, 17.00
Alemanengasse 44, 4018 Basel


'''

Aufbruch nach prrrr
Ein Gesangsprojekt von Marianne Schuppe mit Schülerinnen des Gymnasiums Oberwil

2.März
https://www.garedunord.ch/programm/spielplan[Gare du Nord], Basel


'''

Marianne Schuppe - solo
Stimme, Laute, Uber-bows

Samstag, 20.Januar. 2018, 19.30 Uhr

http://www.zweitagezeit.ch/[Festival Zwei Tage Zeit]
Theater Rigiblick, Germaniastrasse 99, CH - 8044 Zürich


'''

Morton Feldman - Three Voices
Marianne Schuppe, Stimme

Samstag, 13.Januar 2018

https://www.google.fr/search?q=landesmuseum+bonn&gws_rd=cr&dcr=0&ei=HcWzWeCoFcjkUY61rtAI[Zisterzienserausstellung]
http://www.landesmuseum-bonn.lvr.de/de/besucherinfo/besucherinfo_2.html#trigger[Rheinisches Landesmuseum Bonn]
Colmantstraße 14-16, D - 53115 Bonn

'''

Marianne Schuppe - nosongs (2017) UA eines Ausschnitts
Marianne Schuppe, Stimme, Laute, Uber-bows

Montag, 18.Dezember 2017, 18 Uhr

Konzert im Rahmen des Seminars KomponistInnengespräche
Musikwissenschaftliches Seminar der Universität Basel
Petersgraben 27, 4051 Basel


'''

Komponistinnengespräche im Musikwissenschaftlichen Seminar
mit Marianne Schuppe

Montag, 6.November 2017, 18 Uhr

Musikwissenschaftliches Seminar der Universität Baael
Petersgraben 27, 4051 Basel



'''
Selbdritt - Marianne Schuppe, Sylwia Zytynska, Alfred Zimmerlin
http://xploratorium-berlin.de/de/category/improvisationskonzerte/[Exploratorium Berlin]

Donnerstag, 19. Oktober 20 Uhr

Exploratorium, Mehringdamm 55, D - 10961 Berlin


'''

Masterclass Voice - Improvisation
Hochschule für Musik Basel

9.-11. Dezember 2016
Werkstattkonzert 11. Dezember 15 Uhr
Hochschule für Musik, Leonhardsstr. 6, 4051 Basel

'''

Erik Carlson premierres my piece
halbhell for solo violin (2016)

December 9, 2016
St. Diego, USA

'''

Marianne Schuppe - slow songs
for voice, lute, uber-bows

November 24, 2016, 12 pm
http://hcmf.co.uk/[Huddersfield Contemporary Music Festival]
St. Paul's Hall, Huddersfield, England

'''

Marianne Schuppe - slow songs
for voice, lute, uber-bows

November 16, 2016
http://www.impavillon.at/[Pavillon Wels], Austria

'''

Morton Feldman - Three Voices
Marianne Schuppe, voice

November 6, 2016
http://www.tulkinnanvaraista.fi/upcoming-concerts/2016/11/6/a-tulkinnanvaraista-mini-festival[Helsinki Tulkinnanvaraista Festival]
Korjaamo Cultural Factory, Helsinki

'''

Marianne Schuppe - notes from the hill
performed by
Sarah Cranfield (soprano) and Josten Myburgh (sine-tones)

October 8, 2016
Perth, Australia

'''

Improvisationsforum der Hochschule für Musik Basel mit Marianne Schuppe
you and the tube - Subjektive Positionen der Song-Interpretation
zwischen den beiden Weltkriegen in ausgewählten Beispielen

27.{sp} September 2016, 19 Uhr
Hochschule für Musik Basel, Leonhardsstr.6, 4051 Basel

'''

new work :
Marianne Schuppe - notes from the hill
for voice and one instrument

performed by Antoine Beuger
August 21, 2016

http://www.wandelweiser.de/_kalender/calendar.html[Klangraum Düsseldorf 2016]
Himmelgeisterstr. 107, 40227 Düsseldorf

'''

ortlos über die Küste hinaus
Stücke für Stimmen

Marianne Schuppe - Komposition

8.{sp} Juni 2016, 20 Uhr
RAUM, Palmenstr. 4, 4054 Basel

'''

Hans-Jürg-Meier - les mots jaunes
u.a. Werke

Sarah Giger, Traversflöte
Marianne Schuppe, Stimme

27.{sp} Mai 2016, 19.30 Uhr
Musikpodium Zürich, Alte Cigarettenfabrik, Sihlquai 268

'''

slow songs

101.{sp} Atelierkonzert
ww.christophschiller.net/atelier.htm

10.{sp} Mai 2016, 19.30 Uhr
Klingentalstr. 72, 4057 Basel

'''

Antoine Beuger - aus den liedern

Marianne Schuppe, Stimme
http://www.baselsinfonietta.ch/konzerte/saison-15-16/saisonkonzerte/epicycle-5-wohnzimmer-griechenland/[Basel Sinfonietta]
Ltg. Jonathan Stockhammer

24.{sp} April 2016, 19 Uhr
Stadtcasino Basel

'''

Doppelkonzert Feldman / Haubensak

Morton Feldman - Three Voices
Marianne Schuppe, Stimme

22.1.2016, 19.30 Uhr
http://www.overbeck-gesellschaft.de/[Overbeckgesellschaft]
Königstr. 11, D - 22532 Lübeck

'''

Doppelkonzert Feldman / Haubensak

Morton Feldman - Three Voices
Marianne Schuppe, Stimme

20.1.2016, 19.30 Uhr
http://www.tinguely.ch/de.html[Tinguely Museum Basel]

'''

Doppelkonzert Feldman / Haubensak

Morton Feldman - Three Voices
Marianne Schuppe, Stimme

10.12.2015, 20 Uhr
http://www.walcheturm.ch/[Kunstraum Walcheturm]
Kanonengasse 20, 8004 Zürich

'''


Marianne Schuppe - Sapphosongs

30.11 2015, 19.30 Uhr
Zürcher Hochschule der Künste,
Toni Areal, Pfingstweidstr.96,
Konzertsaal 3

'''

Marianne Schuppe - Sapphosongs

24.11.2015, 19.30 Uhr
Archäologische Universität Freiburg i.B.
Tennenbacherstr. 4, D - Freiburg i.B.

'''

Marianne Schuppe - Sapphosongs

13.11.2015, 19.30 Uhr
Mendelssohn Haus,
Goldschmidstr. 12, D - 04103 Leipzig

'''

Marianne Schuppe - Sapphosongs (UA)

1.{sp} November 2015, 19.30 Uhr
Skulpturhalle Basel,
Mittlere Straße 17, 4056 Basel

'''
http://www.wandelweiser.de/_e-w-records/_ewr-catalogue[new release : slow songs]
Marianne Schuppe, voice, lute, e-bows


'''

Marianne Schuppe - slow songs

23.{sp} Oktober 2015, 18 Uhr
Vernissage der Ausstellung von Stephanie Tangerding
und Eva Früh
Palmenstr 4, 4054 Basel

'''

Marianne Schuppe - slow songs
Antoine Beuger - aus den liedern

Marianne Schuppe, Stimme
Antoine Beuger, Flöte
Jürg Frey, Klarinette
Robyn Streb, Viola

9.{sp} August 2015, 17 Uhr
http://www.wandelweiser.de/_concert-series/_klangraum.html[Klangraum], Kunstraum Düsseldorf
Himmelgeisterstr. 107
40225 Düsseldorf

'''

Morton Feldman - Three Voices
für Stimme und Zuspielband

5.{sp} Juni 2015, 21.30 Uhr
Musikhochschule Zürich, Konzertsaal 3,
Toni-Areal, Pfingstweidstr.96
8005 Zürich

'''

Laub
Regula Konrad, Stimme
Marianne Schuppe, Stimme

23.{sp} April 2015  20 Uhr
http://www.gnombaden.ch/[GNOM Baden], Berufsfachschule Martinsberg,
Wiesenstr. 32, 5400 Baden

22.{sp} April 2015, 20.15 Uhr
http://www.pasquart.ch/[Centre PasqArt], Seevorstadt 71-73, 2502 Biel/Bienne

'''

songs
Marianne Schuppe, solo

26.Februar, 20 Uhr
Atelier im Hof, Wilhelmsstr. 21, 42781 Haan

'''

Laub
Regula Konrad, Stimme
Marianne Schuppe, Stimme

18.{sp} Januar 2015, 17 Uhr
Maison 44, Steinenring 44, 4051 Basel


'''

Stirrings Still
Immer noch nicht mehr
nach Samuel Beckett

mit Serena Wey, Mauro Talamini und Marianne Schuppe

4.und 6. Dezember 2014, 20 Uhr
http://www.theatergarage.ch/[Theatergarage], Bärenfelserstr. 20, Hinterhaus, 4057 Basel

'''

the crucial crux of words
Marianne Schuppe, solo
http://www.performingvoice.ch/[Symposium performing voice hkb.bfh]

27.{sp} November 2014
http://www.dampfzentrale.ch/[Dampfzentrale Bern]

'''

Die Geschichte der Musik ist die Geschichte der Dissonanz
Markus Eichenberger im Gespräch mit Thomas Meyer und Marianne Schuppe

NMil, 26.11. 2014
Alte Spinnerei
Anna Heerstr. 5, Suhr

'''


things in singing
Marianne Schuppe, Stimme, Laute, E-Bows

4.,7.,8,November 2014, 20 Uhr
http://www.theatergarage.ch/index.php?id=6[Theatergarage Basel], Bärenfelserstr. 20, 4057 Basel

'''

things in singing
Marianne Schuppe, Voice, Lute, E-Bows

performance + cooperation with
http://www.tyrmi.no/[Hanne Tyrmi] in "The lost thing"

September 27,2014, 2 pm
http://www.haugar.com/[Haugar Verstfold Kunstmuseum], Tonsberg/Norway

'''


Nicht bei Trost. Mikrologien
Lesung für 2 + 1 Stimme
Marianne Schuppe und Franz Dodel

3.{sp} Mai 2014, 17 Uhr
Maison 44, Steinenring 44, 4051 Basel

'''

Yonder
Regula Konrad, Stimme
Marianne Schuppe, Stimme

11.{sp} April 2014, 17 Uhr
Maison 44, Steinenring 44, 4051 Basel

'''

am Fenster
Marianne Schuppe, Komposition und Gesang

10.{sp} April 2014, 20 Uhr
Malzsilo, Werkraum Warteck, Burgweg 15, 4057 Basel

'''

Hitzewelle
Andrea Wolfensberger (Bild) und Marianne Schuppe (Ton)

22.2.-27.4. 2014
Kunstmuseum Solothurn Werkhofstrasse 30, 4500 Solothurn

'''

asunder
eine Musik für Stimmen zum Stummfilm
La chute de la maison Usher (Jean Epstein 1928)

Ensemble für Stimmimprovisation
Konzeption und Leitung
Marianne Schuppe

11.{sp} Februar 2014, 20 Uhr
http://www.theatergarage.ch/index.php?id=6[Theatergarage Basel], Bärenfelserstr. 20, Hinterhaus, 4057 Basel


copyright Ute Schendel

'''

Markus Eichenbergers Domino Orchestra
mit Ute Wassermann und Marianne Schuppe, Stimmen

14.{sp} Dezember 2013, 20 Uhr
Exploratorium Berlin, Mehringdamm 55, 10961 Berlin

'''

Hoffnung - Vortrag und Musik
Musik von Giacinto Scelsi und Hildegard von Bingen

Brigitte Hillmer, Wort
Marianne Schuppe, Gesang

9.12. 2013 12.15 Uhr
Predigerkirche Basel, Totentanz 19

'''

asunder
eine Musik für Stimmen zum Stummfilm
La chute de la maison Usher (Jean Epstein 1928)

Ensemble für Stimmimprovisation
Konzeption und Leitung
Marianne Schuppe

6.{sp} November 2013, 20.30 Uhr
Filmpodium Zürich, Nüschelerstr.11, 8001 Zürich
(18.30 Uhr Vortrag von Fred van der Kooij)
5.{sp} November 2013, 20 Uhr
Theatergarage Basel, Bärenfelserstr. 20, Hinterhaus, 4057 Basel


copyright Ute Schendel
'''

Stirrings Still
Immer noch nicht mehr
nach Samuel Beckett

mit Serena Wey, Mauro Talamini und Marianne Schuppe

30., 31. Oktober 2013  20 Uhr,
8., 9., 10. November 2013  20 Uhr
Theatergarage, Bärenfelserstr. 20, Hinterhaus, 4057 Basel

'''


Amparo
Cooperation with Dias&Riedweg

August 25, 2013, 6.30 pm
Villa de 25 de Agosto, Uruguay


copyright Dias & Riedweg
'''

beinah

Regula Konrad und Marianne Schuppe, Stimmen

24.Mai 2013 20 Uhr, R.A.U.M, Palmenstr.4, 4054 Basel
25.{sp} Mai 2013 20 Uhr, Alte Papiermühle, Benkenstr.61, 5024 Küttigen


'''

Luigi Nono - Guai Ai Gelidi Mostri

Ensemble Diagonal für Zeitgenössische Musik der Hochschule Basel,
Leitung Jürg Henneberger
Ulrike Andersen und Marianne Schuppe, Stimmen
Cornelius Bohn, Live-Elektronik

Volkshaus Basel, Rebgasse 12-14, 4057 Basel
19./20. März 2013 20 Uhr

'''

Morton Feldman - Three Voices

OPENING Festival für Aktuelle Klangkunst Trier
Kultur-und Kommunikationszentrum Trier
1.{sp} Februar 2013 20.30 Uhr

'''

Morton Feldman - Three Voices

http://www.logosfoundation.org/[Stichting Logos], Gent (B)
January 30, 2013 8 p.m.

'''

Marianne Schuppe interpretiert Giacinto Scelsi

Hochschule der Künste Bern
27.November 2012

'''

http://www.zoominfestival.ch/[zoom in] Festival für Improvisierte Musik

Marianne Schuppe, solo

Berner Münster, Bern
13.Oktober 2012 20 Uhr

'''

Songs

Marianne Schuppe, solo

Kirche Deiderode bei Göttingen (D)
7.Oktober 2012 17 Uhr

Kirche Hubenrode / Witzenhausen (D)
6.{sp} Oktober 2012 17 Uhr

'''

Songs

Marianne Schuppe, solo

http://www.raum22.ch/20401.html[raum 22], Kilchberg BL
23.{sp} September 2012 11.30 Uhr

'''

Songs

Marianne Schuppe, solo

Soesterkirkene pa gran, Oslo, Norway
August 18, 2012

'''

GNOM Baden, Performative Aktion und Komposition mit Tanz, Musik und akustischer Installation

17.{sp} Juni 2012 17 Uhr GNOM Baden, Haus Martinsberg, Berufsfachschule Baden BBB, Wiesenstrasse 32, Baden

MARTINSBERG I
Performative Aktion und Komposition mit Tanz, Musik und akustischer Installation mit

Hans Koch – Bassklarinette
Jonas Kocher - Akkordeon
Hans-Jürg Meier – akustische Installation
Dorothea Rust – Tanz Performance
Marianne Schuppe - Stimme
Nadine Schwarz –Tanz Performance
Ivan Wolfe – Tanz Performance


copyright Urs Schnell


Villa Renata, Ausstellungen, Performances, Lesungen, Musik, Gespräche

song, Marianne Schuppe, Stimme, Laute, E-bows

18.{sp} Mai 2012, 21 Uhr Villa Renata, Socinstr.16, 4051 Basel


'''

Giacinto Scelsi - works for solovoice and ensemble

Ensemble Phönix Basel and Marianne Schuppe

9.2.2012 20 Uhr

http://www.google.com/url?q=http%3A%2F%2Fwww.musees.strasbourg.eu%2Findex.php%3Fpage%3Dmamcs&sa=D&sntz=1&usg=AFrqEzfWKIM6JkYvZ6Mr7ikPdy4V8VRCsg[Musée d'Art moderne et contemporain Strassbourg], 1, place Hans Jean Arp
Ensemble Phönix Basel, Conducted by  Jürg Henneberger, Marianne Schuppe, Voice
Giacinto Scelsi - Khoom for 7 Instruments and Voice
Giacinto Scelsi - Pranam I for 12 Instruments, Voice and Tape

'''

Morton Feldman - Three Voices

Marianne Schuppe, Stimme

3.12. 2011 20 Uhr

http://www.google.com/url?q=http%3A%2F%2Fwww.kunsthauswiesbaden.org%2F&sa=D&sntz=1&usg=AFrqEzddr1e-tK8fTxOGQ5AwmTwK7DvBHg[Kunsthaus Wiesbaden], Schulberg 10, 65183 Wiesbaden



'''



WORT
Lesungen und Performances

http://www.mom-aarau.ch/[moments musicaux] Aarau und Forum Schlossplatz Aarau
Sonntag, 13. November 2011 13h30 - 17h30

Mit Sylvia Alexandra Schimag, Sprecherin, und
Marianne Schuppe, Pierre Thoma, Ueli Sager und Peter Schweiger

Forum Schlossplatz und Moments Musicaux Aarau
Forum Schlossplatz, Laurenzenvorstadt 3, 5000 Aarau

'''


Archiv ausgewählter Arbeiten 1986-2011 / selected works 1986 - 2011

icon:file[link=pdf/arbeiten.pdf]
