
== essays

.Leuchtende Losgelöstheit
icon:file[link=pdf/Hirayama.pdf] Nachruf auf Michiko Hirayama (1923 bis 2018) von Marianne Schuppe.

.Aufzeichnen und Erinnern
[%hardbreaks]
https://www.diaphanes.de/titel/aufzeichnen-und-erinnern-performance-chronik-basel-19872006-3372[Musik - Performance - Bewegungen / Ein schleichender Ruck]
Performance Chronik Basel Band II (1987-2006)
Hg. v. Sabine Gebhardt Fink, Muda Mathis, Margarit von Büren
Diaphanes Verlag Zürich/Berlin 2016

.Without
[%hardbreaks]
http://www.dissonance.ch/en/archive/main_articles/1147[dissonance #134, 2016]
Nachdenken über ein «Singen ohne ...» am Beispiel von fünf Songs des 20. Jahrhunderts

.Man kann ihnen auch einfach zuhören
icon:file[link=pdf/bürgin.pdf] Zur Arbeit der Weberin und Textildesignerin Isabel Bürgin, 2016.

.Potentiale des Vergessens
https://www.verlag-koenigshausen-neumann.de/product_info.php/info/p7273_Potentiale-des-Vergessens----48-00.html[Die Ahnung als Motor]
Hrsg.von André Blum, Theresa Georgen, Wolfgang Knapp, Veronika Sellier, Königshausen und Neumann, Würzburg 2012

.Die doppelte Stelle, Singen und Sprechen in der Musik G. Scelsis
icon:file[link=pdf/Doppelte Stelle
.pdf] _Verkörperungen_, Max-Planck-Institut für Wissenschaftsgeschichte, preprint 416, André Blum et al. [Hrsg.], 2011 und im Akademie Verlag, Berlin 2012

.Übersetzen als Arbeitsweise
icon:file[link=pdf/arbeitsweise.pdf] Programmnotiz zu _Hochland- Übersetzungen_, Hans-Jürg Meier, Sarah Giger, Balts Nill, Marianne Schuppe

.Der Wohnwagen, Die Vorbereitung der Musik
icon:file[link=pdf/Dieter-Nanz-Aspekte-der-freien-Improvisation.pdf] _Aspekte der freien Improvisation_ in der Musik, Hrsg. Dieter Nanz, Wolke Verlag, 2011
