
== essays

http://www.diaphanes.de/titel/aufzeichnen-und-erinnern--performance-chronik-basel--19872006--3372[Musik - Performance - Bewegungen / Ein schleichender Ruck]
[literal]
in : Aufzeichnen und Erinnern
Performance Chronik Basel Band II (1987-2006)
Hg. v. Sabine Gebhardt Fink, Muda Mathis, Margarit von Büren
Diaphanes Verlag Zürich/Berlin 2016


.Without
Nachdenken über ein «Singen ohne ...» am Beispiel von fünf Songs des 20. Jahrhunderts
in : http://www.dissonance.ch/en/main_articles/[dissonance #134, 2016]


.Man kann ihnen auch einfach zuhören
Zur Arbeit der Weberin und Textildesignerin Isabel Bürgin, 2016
icon:file[link=pdf/bürgin.pdf]

https://www.verlag-koenigshausen-neumann.de/product_info.php/info/p7273_Potentiale-des-Vergessens----48-00.html[Die Ahnung als Motor]
in : Potentiale des Vergessens, Hrsg.von André Blum, Theresa Georgen, Wolfgang Knapp, Veronika Sellier, Königshausen und Neumann, Würzburg 2012


.Die doppelte Stelle, Singen und Sprechen in der Musik G. Scelsis
in: Verkörperungen, Max-Planck-Institut für Wissenschaftsgeschichte, preprint 416, André Blum et al. [Hrsg.], 2011 und im Akademie Verlag, Berlin 2012



=== Kleine Texte

.Übersetzen als Arbeitsweise
Programmnotiz zu : Hochland- Übersetzungen, Hans-Jürg Meier, Sarah Giger, Balts Nill, Marianne Schuppe
icon:file[link=pdf/arbeitsweise.pdf]

.Der Wohnwagen, Die Vorbereitung der Musik
in : Aspekte der freien Improvisation in der Musik, Hrsg. Dieter Nanz, Wolke Verlag, 2011
