
== interviews

.Interview with the singer Irene Kurka
https://neuemusikleben.podigee.io/114-neue-episode/embed?context=external"[neuemusikleben]

.DIE SUMME Neun Fragen an Marianne Schuppe
icon:file[link=pdf/summe.pdf], https://zeitraeumebasel.com/de/2019/spielplan/de-die-summe[Zeiträume Basel 2019]

.Die Indianer kommen näher
icon:file[link=pdf/dissonanz106.pdf]
Ein Gespräch in Emails mit Michael Kunkel +
dissonanz # 106 Juni 2009

.Potentiale des Vergessens
Ein Gespräch mit Aleida Assmann, André Blum, Wolfgang Knapp, Theresa Georgen, Marianne Schuppe und Veronika Sellier +
du magazin, Januar/Februar 2011

.podcast by Krzysztof Dziuba
icon:link[link="http://www.polskieradio.pl/8/740/Artykul/1700298,Postrockowy-Gorecki-i-inne-dzwieki-Huddersfield-2016"]
Polish Radio about Huddersfield Contemporary Music Festival, including Slow Songs

.Radio SRF: Corinne Holtz im Gespräch mit Marianne Schuppe
icon:link[link=sounds/reflexe.mp3] Reflexe DRS 2 +
{sp}3. April 2007

.Radio SRF: Genie oder Scharlatan, G. Scelsi zum 100. Geburtstag
icon:link[link=sounds/Scelsi-Genie oder Scharlatan 1.mp3] Teil 1, icon:link[link=sounds/Scelsi-Genie oder Scharlatan 2.mp3] Teil 2 +
Schweizer Radio DRS 2, Corinne Holtz im Gespräch mit Fred van der Kooij und Marianne Schuppe
