
== now & then

[%hardbreaks]
.Salz, Lücke, Zelt
Ensemble Voce
Samstag, 2. Juli, 19:30: Stadtkirche, Aarau
Mittwoch, 29. Juni, 19:30: Herz-Jesu-Kirche, Laufen
Sonntag, 26. Juni, 17:00: Kulturkirche am See, Berlin

[%hardbreaks]
.Performance
Marianne Schuppe, Lukas Huber, Vincent Hofmann u.a.
{sp}17. Juni
Kloster Dornach, Amthausstrasse 7, 4143 Dornach

[%hardbreaks]
.Ungehörte Ordnungen
Marianne Schuppe, Stimme
Sergej Tchirkov, Akkordeon
Alfred Zimmerlin, Violoncello
{sp}20. Mai 19.30
Maison 44, Steinenring 44, 4051 Basel

[%hardbreaks]
.colline sur livre
_Knickse Fäden Windpapier_
Marianne Schuppe, Stimme, Laute, Uber-bows
{sp}25. März 19.30
Maison 44, Steinenring 44, 4051 Basel

{sp} +

'''

{sp} +

==== Recent releases


[%hardbreaks]
.a direction out there, readwalking (with) thorau
by Emmanuelle Waeckerlé
Marianne Schuppe, Voice
Stefan Thut, Viol
Edition Wandelweiser https://www.wandelweiser.de/_e-w-records/_ewr-catalogue/ewr2109-10.html[2109/10]
June 2021

[%hardbreaks]
.two songs and one
new solo album released with Takuroku, London
June 3, 2020

https://www.cafeoto.co.uk/shop/marianne-schuppe-two-songs-and-one/[two songs and one]
