
== now & then @ 2023

[%hardbreaks]
.occam ocean XXIX (UA)
von Eliane Radigue
sowie ein neues Werk von Walker/Schuppe (UA)
{sp} 26. April 20h30
Kunstraum Walcheturm, Zürich
ignm Zürich

[%hardbreaks]
.a day in july
Stefan Thut, Marianne Schuppe
{sp} 25. März
Zieblandstraße 45, 80798 München
Klang im Dach, München

[%hardbreaks]
.a day in july ( 2022)
Stefan Thut, Violoncello
Marianne Schuppe, Stimme
{sp} 12. Februar 19h00
Theater Delly, Gerberngasse 11, Solothurn
Doppelkonzert mit Tao Vrhovec Sambolec
Margins of listening (2015)

== now & then @ 2022


[%hardbreaks]
.entrevoix
Stefanie Erni, Stimme
Marianne Schuppe, Stimme
{sp} 10. Dezember 17h00
Schlosserei Nenniger, Zürich

[%hardbreaks]
.Solo Duo Trio
Eva-Maria Karbacher, Saxophone
Lara Süss, Stimme, FX
Marianne Schuppe, Stimme
{sp} 19. November 17h00
Wilde Gallery, Angensteinerstrasse 37, 4052 Basel

[%hardbreaks]
.Salz, Lücke, Zelt (2018)
Ensemble Voce
{sp} 13. November 17h00
Konzertzyklus St. Franziskus Zürich

[%hardbreaks]
.Rebecca Lane, Catherine Lamb, Stefan Thut, Marianne Schuppe, Clara de Asis
November 6, 19h00
Säulenhalle Solothurn

[%hardbreaks]
.Stefan Thut and Marianne Schuppe
{sp} October 29th, 20h15
Amsterdam Wandelweiser Festival
Orgelpark Amsterdam

[%hardbreaks]
.residency walking in air
Will Montgomery, Stefan Thut, Emmanuelle Waeckerle, Carol Watts, Silvia Alexandra Schimag, Antoine Beuger, Leni Dipple, https://cdla.info/2022/10/27/marianne-schuppe-2/[Marianne Schuppe]
Centre de Livres des artistes
September 8-11
St. Yrieux la Perche, France

[%hardbreaks]
.composers meet composers
Els van Riel, Stefan Thut, Emmanuelle Waeckerle, Antoine Beuger, Marianne Schuppe
August 8-14
Le Puid, France

[%hardbreaks]
.entrevoix
Stefanie Erni, voice
Marianne Schuppe, voice
{sp}10. Juli
Biennale d'Art, sentier des passeurs
F- 88210 Quiex / Le Saulcy

[%hardbreaks]
.Salz, Lücke, Zelt (2018)
von Marianne Schuppe
Ensemble https://vokalkunst.ch/vokalkunst/termine/[Voce]
Samstag, 2. Juli, 19:30: Stadtkirche, Aarau
Mittwoch, 29. Juni, 19:30: Herz-Jesu-Kirche, Laufen
Sonntag, 26. Juni, 17:00: Kulturkirche am See, Berlin

[%hardbreaks]
.Laconnex series (UA)
for and with https://insub.org/polytopies/[insub] ensemble
{sp}19.-21. Juni
recording and performance
Laconnex /GE

[%hardbreaks]
.Die Glocke (UA)
Konzeption : Vincent Hofmann und Simon Kindle
Partitur : Lukas Huber und Marianne Schuppe
mit Lukas Huber, Vincent Hofmann, Simon Kindle, Barbara van der Meulen, Marianne Schuppe
{sp}17./18. Juni
Kloster Dornach, Amthausstrasse 7, 4143 Dornach

[%hardbreaks]
.Ungehörte Ordnungen
Marianne Schuppe, Stimme
Sergej Tchirkov, Akkordeon
Alfred Zimmerlin, Violoncello
{sp}20. Mai 19.30
Maison 44, Steinenring 44, 4051 Basel

[%hardbreaks]
.colline sur livre
_Knickse Fäden Windpapier_
Marianne Schuppe, Stimme, Laute, Uber-bows
{sp}25. März 19.30
Maison 44, Steinenring 44, 4051 Basel
