
== now & then @ 2022

[%hardbreaks]
.entrevoix
Stefanie Erni, voice
Marianne Schuppe, voice
{sp}10. Juli
Biennale d'Art, sentier de passeur
F- 88210 Quiex / Le Saulcy


[%hardbreaks]
.Salz, Lücke, Zelt (2018)
von Marianne Schuppe
Ensemble https://vokalkunst.ch/vokalkunst/termine/[Voce]
Samstag, 2. Juli, 19:30: Stadtkirche, Aarau
Mittwoch, 29. Juni, 19:30: Herz-Jesu-Kirche, Laufen
Sonntag, 26. Juni, 17:00: Kulturkirche am See, Berlin

[%hardbreaks]
.Laconnex series (UA)
for and with https://insub.org/polytopies/[insub] ensemble
{sp}19.-21. Juni
recording and performance
Laconnex /GE


[%hardbreaks]
.Die Glocke (UA)
Konzeption : Vincent Hofmann und Simon Kindle
Partitur : Lukas Huber und Marianne Schuppe
mit Lukas Huber, Vincent Hofmann, Simon Kindle, Barbara van der Meulen, Marianne Schuppe
{sp}17./18. Juni
Kloster Dornach, Amthausstrasse 7, 4143 Dornach

[%hardbreaks]
.Ungehörte Ordnungen
Marianne Schuppe, Stimme
Sergej Tchirkov, Akkordeon
Alfred Zimmerlin, Violoncello
{sp}20. Mai 19.30
Maison 44, Steinenring 44, 4051 Basel

[%hardbreaks]
.colline sur livre
_Knickse Fäden Windpapier_
Marianne Schuppe, Stimme, Laute, Uber-bows
{sp}25. März 19.30
Maison 44, Steinenring 44, 4051 Basel
