
== reviews


https://misfitcity.org/?s=marianne+schuppe&submit=Search[Misfit City]


'''

Besprechung von Thomas Meyer / review by Thomas Meyer
http://www.zweitagezeit.ch/[Festival Zwei Tage Zeit]
https://swissmusic.ch/en/read/two-days-time-for-improvised-music/

'''

Marianne Schuppe‘s recital was a hugely refreshing and welcome contrast
to — well, to almost everything else that had been going on.
http://5against4.com/tag/marianne-schuppe/[Simon Cummings] Nov 29, 2016

'''

interview with Robert Worby on BBC and excerpts of Huddersfield concert Nov 24, 2017
http://www.bbc.co.uk/programmes/b0858nv5

'''

podcast by Krzysztof Dziuba / Polish Radio about Huddersfield Contemporary Music Festival, including Slow Songs

http://www.polskieradio.pl/8/740/Artykul/1700298,Postrockowy-Gorecki-i-inne-dzwieki-Huddersfield-2016

'''

Marianne Schuppe’s recital was all about simplicity, subtlety, artistry and authenticity, captured in eleven songs that manage to grip one’s attention while never obviously seeking to, and which commune something important yet keep their meaning diffuse and at something a distance. It was all captivating.http://5against4.com/2016/11/25/hcmf-2016-marianne-schuppe/

'''

Overall, slow songs could be the product of some mythical folk psalter, projecting their respective meanings (and subtexts) via the medium of a cool, measured demeanour. http://5against4.com/2015/11/19/new-releases-jurg-frey-wandelweiser/

'''

The richness and detail that other artists appearing on Wandelweiser achieve with complex harmony is here achieved with a single note.  12/2015
http://www.fluid-radio.co.uk/2015/11/marianne-schuppe/[Cd review by Nathan Thomas / fluid radio]

'''

But Schuppe doesn’t pluck her lute. Instead she uses e-bows to turn a melodic accompanying instrument into an environment, an ancient combination updated to reflect a contemporary preference for objects over stories.
 The Rambler, Tim Rutherford Johnson
 https://johnsonsrambler.wordpress.com/2016/05/04/cd-review-marianne-schuppe-slow-songs-wandelweiser

'''

Mais c’est sans doute quand elle envisage la distance à respecter entre sa voix et le signal électronique, qu’il soit aigu ou grave, que Schuppe gagne toute notre attention..
http://grisli.canalblog.com/archives/2016/01/08/33181216.html[Le son du grisli]

'''

"Beautiful and eerie..."
http://www.thewire.co.uk/issues/383[the wire soundcheck A-Z issue 338]

'''

...Three Voices is, in short, pure hypnotic stillness. For the performer a real challenge for you as concertgoers a must hear. Implementation is provided by the versatile Swiss singer Marianne Schuppe.. Schuppe is anything but a LaBarbara-clone, and from an individualistic reflex gives a private key to implementation: refined, light and taken from a classical singing tradition.

oorgetuige Gent 23.1. 2013

'''

Splendid album and a fascinating inventive approach to four-piece acoustic group improv on Kärpf (AHA 1002) – one of three new items we got recently from Acheulian Handaxe. The four players don’t seem too hurried about rushing into one of those familiar improvising situations where all play at once and are determined to scrabble up the atmosphere with scrapey strings and where percussion is used largely as a battlefield preparation. Instead George Wolf (bass) and Michael Vorfeld (percussion and string instruments) use odd and isolated sounds, and quietly delineate unusual abstract spaces where every horizon is tilted sideways and each man must fare as best he can, balancing on stilts or springs as the occasion demands. In this zone, the “soloists” (and I use the word ironically) Hans Tammen contributes his “endangered guitar” and the vocalist Marianne Schuppe drops in urgent spoken mutterings, perhaps using the German tongue, as rapidly as any sewing machine can patch up your sports coat.

The effect of all this, particularly on the longer tracks, verges on the surreal – when you play this you get more than just an unusual combination of sounds, and the very atmosphere seems charged with genuine mystery, as though all four were facing a smoking gun to the west and a hangman’s noose to the east. This release is renewing my interest in the notion of “dynamic space” in performed music, and a greater sense of co-operation among musical players I doubt I shall meet again in the next 48 hours...

https://handaxe.bandcamp.com/album/k-rpf[Ed Pinsent - The Sound Projector 6/2011]

'''

An hour's worth of solo "song" on this new disc unaccompanied, or joined by mirror images on tape starts off unsettling but not for long. The singer, Marianne Schuppe, has such remarkable control that you begin to hear her vocal lines, and her incredible range, as a musical language all its own, haunting, powerful and, in its own way, very beautiful.

Los Angelos Weekly April 2007

'''

Every once in a while a piece of music comes into your sphere of listening and you wonder how in the world this stuff ever came into being and how you ever missed it. This CD of microtonal voice compositions is possibly one the most intense yet strangely static experiences that have come my way in a long while....The music on this disc is sparse in its execution, being primarily performed by a single voice with the addition of a second on tape for four out of the 13 tracks. This austerity manages to intensify the experience to the point of an almost spiritual level, but at the same time is as ecstatic and pagan as any good orgy. As an insight into the scope of microtonality, it is invaluable as some of the pieces are literally based on one note. Some of the tracks gives one the idea that Diamanda Galas spent some time listening to Scelsi and one of the most interesting things about the CD is that some of these "songs are reinterpretations of instrumental works. Sheer brilliance! (New Albion)

Nilan Perera, Exclaim, Toronto Dec 2006

'''

The opening "Sauh I-IV" (from 1973, for voice with magnetic tape) features layers of Schuppe's voice, in impressive, polyphonic style - a great antidote for those of those of us living in fear of the "operatic wail". Her technique and intelligence inform an innate ability that allows her to move from 'song' to 'sound' to 'speech' in a lyrical and fluid manner."

Forced Exposure Dezember 2005

'''

Marianne Schuppe's lustrous voice imbues the material with a hallowed aura, albeit one without obvious religious hues. Having studied with Scelsi colleague Michiko Hirayama, one can confer a degree of authenticity on to Schuppe's performances, though it should be noted that Scelsi granted substantial interpretative leeway to the performers of his music. Consequently, the line between Scelsi's intentions and Schuppe's conceptions is shrouded. Captivatingly so.
Point of departure September 2007

'''

Stupefacente l'invenzione melodica, da fare invidia a un free-jazzman con quelle frasi interrote o risolte in modo "non consequenziale". Schuppe si esibice persino in movenze danzanti da "swing asmatico". Mai visto e sentito uno Scelsi così !

Il Manifesto, Roma, January17, 2006

'''

Un chant aussi subtil qu'apaisé, magnifiquement rendu par la voix de Marianne Schuppe

Nouveaute, Paris 2007

'''

Portrait von Stefan Drees
https://docs.google.com/a/marianneschuppe.com/viewer?a=v&pid=sites&srcid=bWFyaWFubmVzY2h1cHBlLmNvbXxkZXxneDo3MDI5ODE5ZjM2MjkyMmU5[Imaginäre Narrative]
Marianne Schuppes vokale Kunst der feinen Übergänge

in : Neue Zeitschrift für Musik 03/17

'''

Eine Frauenstimme, allein, gestützt nur von feinen liegenden Klängen, geschützt nur von der englischen Sprache, eine Stimme und elf Lieder: „slow songs“, schlicht, unmittelbar, Enkelinnen jener „Wonderful Widow of Eighteen Springs“ von John Cage. Jener ruhige Song auf drei Tonhöhen aus dem Jahr 1942 mag hier als Vorbild gedient haben, aber Marianne Schuppe, die in Basel lebende Vokalistin, Improvisatorin und Komponistin, geht einen Schritt weiter, dreht die Lieder allmählich aus der Beschränkung auf Weniges heraus, hin auf Weiteres, singt mutig vorwärts, ganz sicher, aber auch so, dass wir spüren, wo sie abwägt, überlegt, vom Wege abkommt, um anderes Terrain zu betreten, alles bedacht und bedachtsam, ohne Eile, ohne Hast, wunderbar, berührend.

Thomas Meyer in Jazz'N'More Jan/Febr. 2016

'''

Die Sängerin Marianne Schuppe ließ einmal mehr mit «aus den liedern» von Antoine Beuger (2007/2008) die Magie der leisen Töne hören. Sie steht weit hinten auf der Bühne und singt nur einzelne Silben, fast ohne Vibrato, zart und klar.

Anja Wernicke, Basellandschaftliche                       Zeitung,26. April 2016

'''

Die Stimme wird zum Anreger für das instrumentale Geschehen und wirkt so aufgrund ihrer Ausdrucksvielfalt auf die Artikulation und Wahl der Instrumente aus, so daß die sieben Gesänge ...sich als zart ausbalancierte kammermusikalische Situationen mit jeweils individueller Atmosphäre erweisen.
Cd Besprechung Giacinto Scelsi, Pranam I+II, Khoom u.a. mit Ensemble Phönix von Stefan Drees, dissonance #130, 2015

icon:file[link=pdf/130_50_cd_std_scelsi.pdf]

'''

...Marianne Schuppes Vermögen, Texte zu inszenieren, ist einzigartig. Gewichtung, Pausen, Sprech- und Singansatz, die Interaktion mit dem kleinen schwarzen Büchlein, aus dem die Textkerne entspringen, stellen die Mittel der Inszenierung dar, die durch Vibraphon und Cello eine passende klangliche Rahmung erhält.

Basellandschaftliche Zeitung, 1.9.08, Andreas Fatton

'''

Ein, wenn nicht der Höhepunkt des Festivals schliesslich der Auftritt des Schweizer Trios "selbdritt"; Die Vokalistin Marianne Schuppe, der Cellist Alfred Zimmerlin und die Vibraphonistin Sylwia Zytynska proben seit Jahren miteinander, haben auch schon eine Cd beim Schweizer Tonkünstlerverein herausgegeben, sind aber gerade erst ein halbes Dutzend mal live aufgetreten. Ja, fast scheint es, als sei ein Publikum für diese spezielle Art der Imrpovisation (ohne jegliche Vorgaben) gar nicht notwendig, so intim, wenn auch keineswegs abweisend klingt diese Musik. Schuppe spricht, singt et cetera aus einem Buch voller Notizen, die beiden Instrumente sprechen, singen....auf ihre Weise dazu, und der Klang von Vibraphon und Violoncello korrespondiert dabei auf erstaunliche Weise. Das Trio bewegte sich mit so traumwandlerischer Sicherheit durch die Zeit, dass es eine Freude war. Folgerichtig schloss ihre Darbietung auf dem Wörtchen "Glück".

Thomas Meyer, Tages Anzeiger Zürich, 2.9.2008, MusikTexte 119, Dezember 2008, Schweizer Musikzeitung 2008

'''

Nicht allzu häufig kommt es vor, dass ich mir nach dem Anhören einer CD die Scheibe gleich noch einmal von vorn anhöre. Mit der neuesten Produktion von Marianne Schuppe ist es mir jedoch so ergangen : nach ihrer Auseinandersetzung mit den archaischen Klängen Giacinto Scelsis hat sich die Sängerin dem gleichsam abstrakten Gebilde von Morton Feldman Three Voices (1982) angenommen und damit neue Massstäbe gesetzt : Im Zusammenwirken von Live-Vortrag und aufgezeichneten Stimmparts leuchtet Schuppe die introvertierte Klangwelt der Komposition aus und erreicht bei der Wiedergabe der unvorhersehbaren Texturänderungen Wirkungen, die unter die Haut gehen. Da werden Augenblicke des minimalen Umschwungs zum grossen Ereignis, etwa dort, wo sich aus den engen Clusterbewegungen des Beginns erstmals die Stimme steil aufsteigend und im Legato in ein höheres Register aufschwingt, aber auch in jenem Moment, wenn nach rund 20 Minuten erstmals der Text "Who'd have thought that snow falls" in die Klänge hineingewoben wird. Die Dichte und intonatorische Exaktheit, aber auch die feinen Wandlungen im Timbre der Stimme und die musikalische Präsenz, mit der Schuppe die zarten Gesten von Feldmans Musik realisiert, sind einfach erstaunlich. Die Sängerin dringt in die Musik ein, bringt Tonhöhenbewegungen und Clusterschichtungen förmlich zum Strahlen, wahrt aber dennoch eine gewisse emotionale Distanz und schafft so das Paradoxon eines sachlich wirkenden Klangbildes von grosser Intensität und Schönheit, das den Hörer nicht kalt lässt.

Stefan Drees, dissonanz #99 September 07

'''

Marianne Schuppe könnte ,Three Voices’ kontemplativ singen, nach innen gerichtet. Darf man das von einer Interpretin erwarten, die das Werk einmal von der Dachkante eines Theaters sang? Ihr Vortrag ist ein ganzes Theater, im positiven Sinn, allein mit den Möglichkeiten der Stimme. Klar und fein nuanciert hört man Zartes und Zerbrechliches, Dunkles und Wehmütiges, Transzendentes, Heiteres, Keckes oder einfach eine frierende Sängerin. Hat man einmal Marianne Schuppe gehört, so möchte man ,Three Voices’ von keinem anderen Interpreten hören. Sie präsentiert ein überaus farbiges Epitaph, ein Epitaph für Morton Feldman. Eine Referenzaufnahme.

Klassik com, Patrick Beck 30.07.2007

'''

Schuppe setzt ihre Fähigkeiten bei der feinen Modulation von Stimmenklängen auch dort ein, wo es weniger um das Singen als um den Umgang mit der Sprechstimme geht. Auf der CD selbdritt - von hier trägt sie zusammen mit den Mitgliedern ihres Improvisationstrios selbdritt Sylwia Zytynska (Vibraphon) und Alfred Zimmerlin (Violoncello) zur Schaffung von Klängen bei, die sich an der Grenze von Musik und Hörstück bewegen. Der von Schuppe meist sprechend vorgetragene Text, collagiert nach Zitaten aus ici von Nathalie Sarraute, führt aufgrund des Umgangs mit den Sprachbruchstücken zu einem ständigen Spiel mit Bedeutungen. Mit feinem instrumentalem Spürsinn kommentieren die beiden Partner die Wortkaskaden oder Loops, die von der Sängerin präzise und durchsichtig vorgetragen werden, wobei die emotional unterschiedlich eingefärbten Stimmsplitter dazu beitragen, die instrumentalen Klänge zu konnotieren, diese aber umgekehrt auch auf den Text zurückwirken und ihm bestimmte emotionale Richtungen verleihen. Die klanglich sehr unterschiedlichen Komponenten aller drei Musiker werden dabei zu einem erstaunlich kohärenten Ergebnis verschmolzen und fügen sich zu einer narrativen Ganzheit, die sich als Suche nach den Möglichkeiten und Koexistenzen von Wort- und Klangbedeutung erweist.

Stefan Drees, dissonanz #99, September 07

'''

[quote, Westfälische Nachrichten, 1.12. 2006]
mit der faszinierenden Sängerin Marianne Schuppe aus Basel.
Es geht Schuppe offenbar um Studien zur Artikulation, höchst virtuose zumal.
Das zeitigt Respekt.


'''

Was Marianne Schuppe...in puncto stimmlicher und emotionaler Intensität leistet, ist phänomenal: Indem sie die Klänge und Laute wie einen Tonklumpen mit ihrer Stimme bearbeitet, rückt sie die skulpturhaften Qualitäten in den Vordergrund. In ihrer Interpretation von Sauh I-IV (1973) wird das Zusammenwirken von Stimme und ein- bis dreifachen elektronischen Stimmzuspielungen zu einem immer dichter und plastischer gearbeitetem Klangband, das dennoch aufgrund der nuancierten Farb-und Artikulationsgebungen im Inneren flexibel bleibt. Erstaunlich ist auch, was die Sängerin aus den Zyklen Taiagarù (1962) und Hô (1960) herauszuholen versteht, indem sie ganz bewusst die zerklüfteten Atembögen artikuliert und ihnen einen kraftvollen Anstrich verleiht, der auch viel dazu beitragen könnte, die mystifizierenden Klischees über Scelsis Komponieren auszuräumen.

Stefan Drees / positionen, 8/2006

'''

[quote,Helmut Peters / Neue Zeitschrift für Musik 5/2006 ]
hat die wohl anerkannteste Interpretin (Scelsis) Vokalmusik, Marianne Schuppe, ihre Einspielung unter das vieldeutige Motto "Die Kunst des Liedes von Giacinto Scelsi" gestellt... Sie überträgt nicht den Instrumentalklang auf ihre Stimme, sondern überführt ihn in eine eigene, eigenen Gesetzen gehorchende Welt von Lautäusserungen, wobei die Klarheit, ja die Reinheit ihres bewegenden Soprans jede phonetische Geste veredelt. Das Rufen und Schreien, das schwere Atmen und figurative Schwanken in Taiagarù überschreitet nicht die von Schuppe, wohlweislich nicht von Scelsi gesteckten Grenzen. Auf diese Art gelingt der Sängerin eine Natürlichkeit, die sich völlig losgelöst von konstruierter, auskomponierter und damit in gewissem Masse auch starrer Musik bewegt.

'''


[quote, Michael Eidenbenz / dissonanz #96, 12/06]
Das Ergebnis ist Musik, die gleichsam den Moment ihrer Entstehung wiedergibt....Marianne Schuppe hat bei Michiko Hirayama studiert, kann sich also auf Authentizität berufen, sofern dies bei der interpretatorischen Variantenvielfalt überhaupt möglich ist, die Scelsis Partituren anbieten. Dennoch zeugt ihre Einspielung von einer Interpretationshaltung einer "zweiten Generation" gewissermassen. Von einer Phase der Scelsi-Rezeption jedenfalls, die die Heiligsprechung des Meisters ebenso überwunden hat wie jede Neigung zu selbst-darstellerischem und sendungsbewusstem Entdeckerstolz.


'''

Die introspektive Seite der Musik von Giacinto Scelsi (1905-1988) ist eindeutig überschätzt. Nun präsentiert die in Basel lebende tiefe Sopranistin Marianne Schuppe eine CD mit selten aufgeführten Solo-Gesängen in einer Interpretation, die mit der üblichen Scelsi-Kontemplation kaum etwas gemein hat. Schuppe pflegt Scelsis Vokalmusik in sehr willkommener Betonung ihres Sprachcharakters, ihrer enormen Körperlichkeit. Eine der lebendigsten Scelsi-Aufnahmen im Jubeljahr seines 100. Geburtstags.

Michael Kunkel in / Tagesanzeiger, Zürich, 6.Dezember 2005


'''

Zur wohl intensivsten Tonkünstlerfeststunde geriet Musik am Bau mit Marianne Schuppe und Peter Vittali: Schuppe entliess Feldmans "Three Voices" aus seinem Kammerkonzertsaaldasein, als sie das Werk von der Dachkante des Théâtre du Chrochetan aus ins Städtchen hinein sang, die Feldman-Intimität sich mit der freitagabendlichen Monthey-Musik paaren liess.

Michael Kunkel / Tagesanzeiger Zürich, 8.9.2004

'''

".... in der Gare du Nord Feldmans geniales "Three Voices". M.S. sang ihren Part in höchster Konzentration...langer Beifall für die ausgezeichnete Sängerin.

N.Cybynski / Basellandschaftliche Zeitung, 7.4.2004

'''

[verse,Frankfurther Rundschau 8.5.01]
eine Stimmung, die sich in der Interpretation des Klangforums unter der präzisen und fordernden Leitung von Roland Kluttig in Pranam I von G. Scelsi für Stimme, zwölf Instrumente und Tonband fortsetzte. Den schwierigen Gesangspart meisterte Marianne Schuppe in bewundernswerter Sicherheit.

'''

Wirkliche Freiheit indessen vernahm man in der Improvisation von Marianne Schuppe (Stimme), Sylwia Zytynska (Perkussion) und Alfred Zimmerlin (Violoncello). Das eingespielte Trio schuf konzis umrissene Stimmungs- und Aktionsbilder, demonstrierte Spiellust und die Ueberraschungsgabe blitzschnellen Reagierens. Ihre Musik hatte Delikatesse, Charakter, Groove.

Benjamin Herzog / Basler Zeitung 22.5.01

'''

Marianne Schuppe verfügt über eine leuchtkräftige, wandlungsfähige Stimme, die risikofreudig schwierige Intervalle meisterte und den Raum mit vibrierenden vokalen Linien füllte. Obwohl die beiden vorgestellten Zyklen Hô und Taiagarù unbegleitet und einstimmig waren, erschien der Gesang im Ineinandergreifen der verschiedenen Register gleichsam mehrstimmig. Faszinierend, wie restlos die Stücke sich der Stimme anpassten und wie lückenlos die Sängerin sich Scelsis Musik anverwandelte.

Martina Wohltat in / Basler Zeitung, 8.2.99

'''

Es gibt noch ungewöhnliche Positionierungen neben der Bühne, die unverbraucht wirken. Die beiden Frauen (Dorothea Schürch und Marianne Schuppe) setzten sich hoch oben über dem Publikum in die zwei entgegengesetzten Ecken auf die Galeriekante; dahinter liess eine Fensterscheibe das blaue helle Himmelslicht eines Septembertages einfallen, und die Zuschauer konnten Flugzeuge auf dem Weg nach Irgendwohin betrachten. So wie sich die beiden Frauen in ihre Umgebung einbetteten, so scheinen sie auch ein offenes Ohr für ihre direkte Umwelt zu haben. Ihre Wort- und Silbenspiele sind exakt auf die lautmalerische Seite untersucht und ausgehorcht. Zum ersten Mal in diesem Stimmenfestival nahm man auch zischende, sprudelnde, gurgelnde, schwabernde und vor allem nackte Stimmen wahr - eine Wohltat nach so viel gepflegtem Kunstgesang; faszinierend, wie sich die Vokalistinnen in den Texten einrichteten, ...

Christina Omlin / Dissonanz, Nr.50, Nov. 96

'''


Hoch oben auf den Balkongeländern bei den Fenstern (man bekommt fast Angst, sie könnten abstürzen) sitzen zwei Frauen, singen, rezitieren; sie lallen, korrigieren dabei das Programmheft, skandieren, deklamieren. Und es ist eine Freude ihnen zuzuhören, weil sie mit Phantasie und Witz dahintergehen...

Thomas Meyer / Tages Anzeiger, 9.9.96

'''

"...in Rümlingen, gerade wie bei den an der Reckstange kopfüberhängenden Frauen Marianne Schuppe und Dorothea Schürch, die in ihrem köstlichen Kabinettstück "Wellen" vordemonstrierten, dass man (oder frau) etwas Verkehrtes auch andersrum sagen kann.

David Wohnlich / Basler Zeitung, 27.8.96

'''

Zwei Lautsprecher, dazwischen ein Notenpult : karges Instrumentarium für die grandiose Schweizer Sopranistin Marianne Schuppe, die sich in Hamburg der Tour de Force dieses schwierigen Stückes stellte.

Jan-Barra Henschel / Hamburger Anzeiger 14.11.94

'''

[verse, Ludolf Baucke / Hannoversche Allg. Zeitung, 15.4.93]
und diese vier Vokalisen trug Marianne Schuppe mit aller gebotenen Konzentration im neuen Auditorium vor. Sie setzte damit Masstäbe für eine ebenso anregende wie präzise Präsentation musikalischer Moderne.


'''

Die Sopranstimme gleitet in sphärische Höhen, schwebt sirenengleich. Oder sie vollführt abenteuerliche Intervallsprünge, geht auch ins Geräuschhafte über. Sie beherrscht bewundernswert die Gesangstechniken der Neuen Musik und die Praktiken des Avantgarde-Jazz, der improvisierten Musik....Dieses Trio um die Basler Sängerin Marianne Schuppe gehörte sicher zu den Höhepunkten der"off lines two".....

Badische Zeitung, 24.3.93

'''

...wie die sensationelle Stimme der Baslerin Marianne Schuppe. Mit flirrenden Vokalisen durchschreitet ihre Stimme ungeahnte Gefühlswelten. Ihr beachtliches Sopran, unterstrichen durch gewagte Intervallsprünge, geht fliessend in Geräuschhaftes über.

Jazzpodium, Mai 93

'''

Bei Marianne Schuppe, "nur" die Stimme, als Instrument benutzt, elementare Kraft und intelligenter Einsatz, so prägt ihr Gesangsvolumen die Interpretationen in einer beeindruckenden Dichte.

Trierischer Volksfreund, 22.7.93

'''

Marianne Schuppe brilliert mit einem virtuosen Instrumentalgesang, der auf eine klassische Schulung, auf Techniken zeitgenössischer Musik weist. Mühelos springende, glissandierende Vokalisen, die bei aller "Sprödigkeit" sinnlich, hautnah bleiben.


Badische Zeitung, 30.1.92

'''

"Die Stimme (Marianne Schuppe ist eine ebenso exellente Sprecherin wie Sängerin) wird hier zum Instrument aller Instrumente, gibt strahlend, seufzend, flüsternd, lallend, zischend, schnalzend, summend oder in abgerissenen Silben, frei strömend oder akustisch verändert durch Bewegungen mit der vorgehaltenen Hand alles wieder, was menschliche Empfindung umschreibt.

Zürcher Oberländer, 29.10.91

'''

Da Marianne Schuppe vom ersten bis zum letzten Ton ihres Programms ohne jegliche Begleitung singt, kommt ihr beachtliches stimmliches können voll zur Geltung.Die dargebotenen Entwicklungen einzelner Töne, verbunden mit Intervallen und der Artikulation verschiedener Vokale und Konsonanten, entfalten sich in den besonderen akustischen Gegebenheiten des Gewölbes zu immer neuen Klängen voller Klarheit und Kraft.

Der Bund, 21.1.90
