
[[teaching]]
== mentoring for composer-performers

Since the middle-eightees I have enjoyed passing on my experiences as a singer, performer and
teacher to others.

I propose mentoring sessions adressed to composer-performers working with voice and words.


.My background in teaching
I have trained singers, dancers, teachers and other enthusiasts in developing their voices in groups
and individual lessons. I have worked in theatre-and dance-productions as a voice teacher and
musical advisor and I have given masterclasses and lectures on my work in Europe and Asia.

From 1995-2010 I have educated singers and speakers in the Atem-Tonus-Ton-method and voice-
improvisation in Switzerland, Germany and Japan and have been working as a guest-lecturer for
voice and improvisation at the FHNW University of Music in Basel and other swiss university-music departments. I also have been the director of an advanced voice ensemble, focused on
improvisation and staged several performance-projects.


.Conditions
Sessions take place in a series of 3 or 5 meetings in Basel, one to one
and are based on your personal needs and questions.
We meet in person in my atelier in Basel. 

Financial terms to be discussed on case by case basis.

If you wish to come in an ensemble working on a piece, we will work out an arrangement.

If you are interested please <<contact, contact>> me.
If you need a place to stay in Basel I can help finding accomodation.
[%hardbreaks]
{nbsp}
{nbsp}