= Bridging words and music
:includedir: _includes
:imagesdir: ./images
:icons: font
:toc: left
:toc-title:
:nofooter:
:sectnums:
:figure-caption!:
:sectnums!:
:docinfo: shared

link:/../index.html[icon:home[]] 

[Abstract]
My interest in voice draws me into the area between music and language. An area which I see as the coast between words and music, where the grain of language and the fluidity of sound converge. I have wandered in this area since 1995 and my interest has been:

- exploring the simultaneity of sound and meaning within the words in text only works like colline
sur livre. Here sound and meaning are inextricable interwoven.
- exploring the intersections of sound and meaning in the interplay with an instrument. Here the
e-pont serves as a bridge between pure sound and voice, allowing shades of
transparency and occlusion of one or the other.
- exploring the relation between words and music through text-scores and oral transmission.
Here words serve as a medium to convert ideas that can not be described otherwise.

== {nbsp}

=== colline sur livre (2023 - )

link:/../csl/index.html[_Colline sur livre_] is an ongoing work to observe and suss the intersections, overlays and dimensions between words and music on the
basis of the growing text-corpus _colline sur livre_. 
This process is facilitated by a lute and cableless mini-set of electronics, a device that I call e-pont, because it serves as a bridge between words and music.

=== wippe (2025)
text-publication with Verlag Klingental, Basel, an editor, that features works in the intersection between
words and music.

=== Aus dem Zeltbuch (2023)
was created in co-authorship with cellist Deborah Walker as a related counterpart and to be played in a
programme with Eliane Radigue‘s OCCAM RIVER XXIV. +
In the area between music and langage _Aus dem Zeltbuch_ is the incarnation of langage in speaking voice. +
The piece unfolds a surface of words-sounds textures in low dynamics on the edge of acoustic
intelligibility. This work is questioning the perception of language in a musical context by creating
bilingual areas of sound. As words and sounds are superimposed they may unclose a sounding path
through narration, meaning and understandibility. https://soundcloud.com/marianne-schuppe/aus-dem-zeltbuch-extrait1[extract]


=== a day in july (2023)
Marianne Schuppe, voice & text +
Stefan Thut, cello, pipe, pencil and paper

Developed and conducted with cellist and composer Stefan Thut +

In _a day in July_, words and sounds alternate and overlap in certain dependencies. Decisions are made by
listening to the decisions and sounds of the partner. One triggers the next in an act of translation. And that
in turn triggers the next and so on.
The words could be seen as a collection from the particular place of each playing. As each realization of
the piece takes place in a new place, the words also change. And so do the pitches and harmonies of the
cello, because they relate to each other.
The trace of each performance is a score, which will never be played again. The next time a day in July
continues with the same plan in a yet unknown direction filtered through a new place and time. +

Duration : 45‘-60‘ +

a _day in july_ was first performed in Orgelpark Amsterdam in 2023 in the Wandelweiser Festival.
It was recorded in October 2024 during a residency at GMEA, Albi in the Temple Protestante.


In _a day in july_ folgen und überlagern sich Wörter und Klänge in bestimmten Abhängigkeiten.
Entscheidungen werden in Konsequenz zu den Entscheidungen und Klängen des Mitspielers getroffen.
Das eine löst das nächste in einem Akt der Übersetzung aus. Und das wiederum löst das nächste aus und
so weiter.
Die Worte könnten als eine Sammlung des jeweiligen Spielorts gesehen werden. Jede Umsetzung des
Stücks an einem neuen Ort führt zu neuen Worten. Das gilt auch für die Tonhöhen und Harmonien des
Cellos, denn sie stehen in Beziehung zu den Wörtern.
Die Spur jeder Aufführung ist eine Partitur, die nie wieder gespielt wird. Beim nächstn Mal geht _a day in
july_ mit demselben Plan in eine noch unbekannte, von Ort und Zeit gefärbte Richtung weiter.

=== entrevoix I (2024)
was developed for the duo with singer Stefanie Erni. A list of words in german, english and french serves
as a subterrainian element shaping the sounds of the singers without becoming intelligible.

=== Salz, Lücke, Zelt (2019)
for 8 mixed voices +
commissioned by Ensemble Voce, Basel,

=== slow songs - nosongs (2015 / 2018)
solo voice with lute and e-ponts


=== der blumen ( 2017)
for any number of voices

=== notes from the hill (2015/2019)
for voice and one instrument

=== temps ( 1998)
commissioned by Schweizer Tonkünsterverein

=== wandern (1995)
co- composition with Willy Daum

