= works
:includedir: _includes
:imagesdir: ./images
:icons: font
:toc: left
:toc-title:
:nofooter:
:sectnums:
:figure-caption!:
:sectnums!:
:docinfo: shared
:linkcss:
:copycss!:
:stylesheet: theme.css
:stylesdir: /current-theme

link:/../index.html[icon:home[]] 

Listening to a voice, one may hear sounds or words. Words are linked to a specific language and understanding. Sounds may hide the voice as a human source. Though sounds are not bound to a specific vocabulary, they are as well carrying meaning, intended or not.
Words and sounds constitute the presence of voice and do not exist independently. Both have a specific physicality. They interact, within or outside language. Together they unfold the complexity of singing.

My compositions are rooted in my practise as a singer, vocalist, writer and teacher.
Find a selection of my pieces here:

link:/works/composer-performer.html[composer-performer] +
link:/works/composing-for-voices.html[composing for voices] +
link:/works/collective-and-interdisciplinary-work.html[collective and interdisciplinary works] +
link:/works/bridging.html[bridging words & music] +
link:/works/extending.html[extending the idea of concert]

link:/../index.html[icon:home[]]
